package src.main.java.Category_story6_7;

import javafx.fxml.FXML;
import javafx.scene.control.Label;
import javafx.scene.layout.VBox;
import javafx.scene.text.Font;
import javafx.stage.Stage;

/**
 * This controller manages the analysis report window in the Transaction Management System.
 * It displays a detailed analysis report generated by the AI service and provides a user-friendly interface to view the report.
 * The controller handles the display of the report text and the close button functionality.
 *
 * @author Wei Chen
 * @version 1.0
 */
public class AnalysisReportController {
    @FXML
    private VBox reportContent; // VBox container for the report content

    /**
     * Sets the report text to be displayed in the analysis report window.
     * @param reportText The analysis report text to be displayed.
     */
    public void setReportText(String reportText) {
        Label reportLabel = new Label(reportText); // Create a label to display the report text
        reportLabel.setWrapText(true); // Enable text wrapping for the label
        reportLabel.setFont(new Font(14)); // Set the font size to 14
        reportContent.getChildren().add(reportLabel); // Add the label to the VBox container
    }

    /**
     * Handles the close button click event.
     * Closes the analysis report window.
     */
    @FXML
    private void handleClose() {
        // Close the window
        Stage stage = (Stage) reportContent.getScene().getWindow(); // Get the current stage
        stage.close(); // Close the stage
    }
}